### 회원가입
POST localhost:8080/signup
Content-Type: application/json

{
  "username": "jinho",
  "password": "Pass1234!",
  "nickname": "mentos"
}

### 로그인
POST localhost:8080/signin
Content-Type: application/json

{
  "username": "jinho",
  "password": "Pass1234!"
}